# Generated by Django 3.2 on 2024-01-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='portions',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество порций'),
            preserve_default=False,
        ),
    ]
