# Generated by Django 3.2 on 2024-01-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingcart_portions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='portions',
            new_name='portions_to_shop',
        ),
    ]
