# Generated by Django 3.2 on 2023-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230610_1652'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipes',
            name='unique_user_fav_recipe_pair',
        ),
        migrations.RenameField(
            model_name='favoriterecipes',
            old_name='fav_recipe',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_fav_recipe_pair'),
        ),
    ]
